# Emission: IR -> Playwright TypeScript. Mirrors src/codegen.rs and Codegen.cs.
#
# Generated tests never talk to raw Playwright locators. They call into the
# hand-written D365 runtime helper, so all the ugly async/blocking-state
# handling stays in one maintainable place instead of being smeared across
# thousands of generated lines.
#
# Every number that reaches the output goes through InvariantCulture. The three
# implementations are held to byte-identical output, and a machine with a comma
# decimal separator would otherwise quietly disagree with the other two.

Set-StrictMode -Version Latest

$script:Invariant = [System.Globalization.CultureInfo]::InvariantCulture

function ConvertTo-InvariantString {
    param([Parameter(Mandatory)] [int] $Value)
    return $Value.ToString($script:Invariant)
}

function ConvertTo-PascalCase {
    <#
        .SYNOPSIS
        The generated file name. Mirrors Casing.cs, which in turn reproduces
        what `heck` does in the Rust build - including that an all-caps run
        lowercases after its first letter (PO -> Po) and that a digit never
        starts a new word (foo2bar stays one word).
    #>
    param([AllowEmptyString()] [string] $Text)

    if ($null -eq $Text) { $Text = '' }

    $words = [System.Collections.Generic.List[string]]::new()
    $current = [System.Text.StringBuilder]::new()

    $flush = {
        if ($current.Length -gt 0) {
            $words.Add($current.ToString())
            [void] $current.Clear()
        }
    }

    for ($i = 0; $i -lt $Text.Length; $i++) {
        $c = $Text[$i]

        $isAlnum = ($c -ge 'a' -and $c -le 'z') -or ($c -ge 'A' -and $c -le 'Z') -or ($c -ge '0' -and $c -le '9')
        if (-not $isAlnum) { & $flush; continue }

        if ($current.Length -gt 0) {
            $prev = $current[$current.Length - 1]
            $prevUpper = $prev -ge 'A' -and $prev -le 'Z'
            $cUpper = $c -ge 'A' -and $c -le 'Z'

            if (-not $prevUpper -and $cUpper) {
                & $flush
            }
            elseif ($prevUpper -and $cUpper -and ($i + 1) -lt $Text.Length) {
                $next = $Text[$i + 1]
                if ($next -ge 'a' -and $next -le 'z') { & $flush }
            }
        }

        [void] $current.Append($c)
    }

    & $flush

    $builder = [System.Text.StringBuilder]::new()
    foreach ($word in $words) {
        [void] $builder.Append([char]::ToUpperInvariant($word[0]))
        for ($i = 1; $i -lt $word.Length; $i++) {
            [void] $builder.Append([char]::ToLowerInvariant($word[$i]))
        }
    }

    return $builder.ToString()
}

function ConvertTo-PlaywrightSpec {
    <#
        .SYNOPSIS
        Generate the spec, the data module and the file stem for a test case.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $TestCase,
        [Parameter(Mandatory)] $Cases,
        [ValidateSet('annotate', 'fail', 'comment')]
        [string] $OnUnsupported = 'annotate'
    )

    $stem = ConvertTo-PascalCase $TestCase.Name

    $body = [System.Text.StringBuilder]::new()
    Write-IrActions -Actions $TestCase.Actions -Indent 2 -OnUnsupported $OnUnsupported -Output $body

    return [pscustomobject]@{
        Spec = (Format-SpecFile -TestCase $TestCase -Stem $stem -Body ($body.ToString().TrimEnd()))
        Data = (Format-DataFile -Cases $Cases)
        Stem = $stem
    }
}

function Format-SpecFile {
    param([Parameter(Mandatory)] $TestCase, [Parameter(Mandatory)] [string] $Stem, [AllowEmptyString()] [string] $Body)

    $actionCount = Measure-IrActions $TestCase.Actions
    $todoCount = Measure-IrMatching $TestCase.Actions 'unsupported'

    $recordingName = ConvertTo-CommentSafe $TestCase.Name
    $testTitle = ConvertTo-EscapedTemplateLiteral $TestCase.Name

    $todoSuffix = ''
    if ($todoCount -gt 0) {
        $todoSuffix = ", $(ConvertTo-InvariantString $todoCount) unmapped - search for TODO(rsat2pw)"
    }

    $b = [System.Text.StringBuilder]::new()
    [void] $b.Append("// ---------------------------------------------------------------------------`n")
    [void] $b.Append("// Generated by rsat2pw from the Task Recorder recording `"$recordingName`".`n")
    [void] $b.Append("// $(ConvertTo-InvariantString $actionCount) action(s)$todoSuffix.`n")
    [void] $b.Append("//`n")
    [void] $b.Append("// Do not hand-edit: regenerate instead. Durable changes belong in the runtime`n")
    [void] $b.Append("// helper (runtime/d365.ts), which is where every D365 quirk is handled.`n")
    [void] $b.Append("// ---------------------------------------------------------------------------`n")
    [void] $b.Append("`n")
    [void] $b.Append("import { test } from '@playwright/test';`n")
    [void] $b.Append("import { D365 } from '../runtime/d365';`n")
    [void] $b.Append("import { cases } from './$Stem.data';`n")
    [void] $b.Append("`n")
    [void] $b.Append("for (const params of cases) {`n")
    [void] $b.Append("  test(``$testTitle [`${params.__case}]``, async ({ page }) => {`n")
    [void] $b.Append("    const d365 = await D365.open(page);`n")
    [void] $b.Append("`n")
    [void] $b.Append($Body)
    [void] $b.Append("`n")
    [void] $b.Append("  });`n")
    [void] $b.Append("}")

    return $b.ToString()
}

function Format-DataFile {
    param([Parameter(Mandatory)] $Cases)

    $b = [System.Text.StringBuilder]::new()
    [void] $b.Append("// ---------------------------------------------------------------------------`n")
    [void] $b.Append("// Generated by rsat2pw. Test data source: $($Cases.Source)`n")
    [void] $b.Append("//`n")
    [void] $b.Append("// This is the RSAT parameter file's replacement. Add rows here (or regenerate`n")
    [void] $b.Append("// from an updated workbook) to run the same recording against more data.`n")
    [void] $b.Append("// ---------------------------------------------------------------------------`n")
    [void] $b.Append("`n")
    [void] $b.Append("export type Params = {")

    foreach ($field in $Cases.Fields) {
        [void] $b.Append("`n  ${field}: string;")
    }

    [void] $b.Append("`n};`n")
    [void] $b.Append("`n")
    [void] $b.Append("export const cases: (Params & { __case: string })[] = [")

    foreach ($row in $Cases.Rows) {
        [void] $b.Append("`n  {")
        [void] $b.Append("`n    __case: '$(ConvertTo-EscapedTs $row.Label)',")

        foreach ($field in $Cases.Fields) {
            $value = ''
            if ($row.Values.ContainsKey($field)) { $value = $row.Values[$field] }
            [void] $b.Append("`n    ${field}: '$(ConvertTo-EscapedTs $value)',")
        }

        [void] $b.Append("`n  },")
    }

    [void] $b.Append("`n];")

    return $b.ToString()
}

function Write-IrActions {
    param(
        [Parameter(Mandatory)] [AllowNull()] [AllowEmptyCollection()] $Actions,
        [Parameter(Mandatory)] [int] $Indent,
        [Parameter(Mandatory)] [string] $OnUnsupported,
        [Parameter(Mandatory)] $Output
    )

    foreach ($action in $Actions) {
        Write-IrAction -Action $action -Indent $Indent -OnUnsupported $OnUnsupported -Output $Output
    }
}

function Write-IrAction {
    param(
        [Parameter(Mandatory)] $Action,
        [Parameter(Mandatory)] [int] $Indent,
        [Parameter(Mandatory)] [string] $OnUnsupported,
        [Parameter(Mandatory)] $Output
    )

    $pad = ' ' * ($Indent * 2)

    switch ($Action.Op) {
        'navigate' {
            Add-RuntimeCall $Output $pad "navigate('$(ConvertTo-EscapedTs $Action.MenuItem)', '$($Action.Kind)')"
        }

        'withForm' {
            Add-CodeLine $Output $pad "await d365.withForm('$(ConvertTo-EscapedTs $Action.FormName)', async () => {"
            Write-IrActions -Actions $Action.Children -Indent ($Indent + 1) -OnUnsupported $OnUnsupported -Output $Output
            Add-CodeLine $Output $pad '});'
        }

        'test.step' {
            Add-CodeLine $Output $pad "await test.step('$(ConvertTo-EscapedTs $Action.Label)', async () => {"
            Write-IrActions -Actions $Action.Children -Indent ($Indent + 1) -OnUnsupported $OnUnsupported -Output $Output
            Add-CodeLine $Output $pad '});'
            [void] $Output.Append("`n")
        }

        'click' {
            Add-RuntimeCall $Output $pad "click('$(ConvertTo-EscapedTs $Action.Control)', '$(ConvertTo-EscapedTs $Action.ControlType)')"
        }

        'tab' { Add-RuntimeCall $Output $pad "tab('$(ConvertTo-EscapedTs $Action.Control)')" }

        'setField' {
            Add-RuntimeCall $Output $pad ("setField('$(ConvertTo-EscapedTs $Action.Control)', " +
                "$(ConvertTo-TsExpression $Action.Value), '$(ConvertTo-EscapedTs $Action.ControlType)')")
        }

        'setGridCell' {
            Add-RuntimeCall $Output $pad ("setGridCell('$(ConvertTo-EscapedTs $Action.Grid)', " +
                "'$(ConvertTo-EscapedTs $Action.Column)', $(ConvertTo-InvariantString $Action.Row), " +
                "$(ConvertTo-TsExpression $Action.Value), '$(ConvertTo-EscapedTs $Action.ControlType)')")
        }

        'openLookup'   { Add-RuntimeCall $Output $pad "openLookup('$(ConvertTo-EscapedTs $Action.Control)')" }
        'commitLookup' { Add-RuntimeCall $Output $pad "commitLookup('$(ConvertTo-EscapedTs $Action.Control)')" }

        'selectRow' {
            Add-RuntimeCall $Output $pad "selectRow('$(ConvertTo-EscapedTs $Action.Grid)', $(ConvertTo-InvariantString $Action.Row))"
        }

        'markRow' { Add-RuntimeCall $Output $pad "markRow('$(ConvertTo-EscapedTs $Action.Grid)')" }
        'openRow' { Add-RuntimeCall $Output $pad "openRow('$(ConvertTo-EscapedTs $Action.Grid)')" }

        'filter' {
            Add-RuntimeCall $Output $pad ("filter('$(ConvertTo-EscapedTs $Action.Control)', " +
                "'$(ConvertTo-EscapedTs $Action.Field)', '$(ConvertTo-EscapedTs $Action.Label)', " +
                "'$(ConvertTo-EscapedTs $Action.Operator)', $(ConvertTo-TsExpression $Action.Value))")
        }

        'selectTreeItem' {
            Add-RuntimeCall $Output $pad ("selectTreeItem('$(ConvertTo-EscapedTs $Action.Control)', " +
                "$(ConvertTo-TsExpression $Action.Path))")
        }

        'expandTreeItem' {
            Add-RuntimeCall $Output $pad ("expandTreeItem('$(ConvertTo-EscapedTs $Action.Control)', " +
                "$(ConvertTo-TsExpression $Action.Path))")
        }

        'shortcut'     { Add-RuntimeCall $Output $pad "shortcut('$(ConvertTo-EscapedTs $Action.Name)')" }
        'resetFilters' { Add-RuntimeCall $Output $pad "resetFilters('$(ConvertTo-EscapedTs $Action.Control)')" }
        'closeForm'    { Add-RuntimeCall $Output $pad 'closeForm()' }

        'expectValue' {
            Add-RuntimeCall $Output $pad ("expectValue('$(ConvertTo-EscapedTs $Action.Control)', " +
                "$(ConvertTo-TsExpression $Action.Expected))")
        }

        'marker' { Add-CodeLine $Output $pad "// $(ConvertTo-CommentSafe $Action.Text)" }

        # Understood and deliberately not replayed. It still leaves a trace in
        # the generated file: a step that vanishes without a word is
        # indistinguishable from one the converter never saw.
        'skipped' {
            Add-CodeLine $Output $pad ("// rsat2pw: skipped '$(ConvertTo-CommentSafe $Action.RawKind)' - " +
                "$(ConvertTo-CommentSafe $Action.Detail)")
        }

        # `Props` carries the untruncated bag for the conversion report; the
        # emitted TODO deliberately uses the short `Detail` instead.
        'unsupported' {
            $message = "could not map Task Recorder action '$($Action.RawKind)' ($($Action.Detail))"
            $literal = ConvertTo-EscapedTs $message

            Add-CodeLine $Output $pad "// TODO(rsat2pw): $(ConvertTo-CommentSafe $message)"

            switch ($OnUnsupported) {
                'comment' { }
                'annotate' {
                    Add-CodeLine $Output $pad ("test.info().annotations.push({ type: 'rsat2pw-todo', " +
                        "description: '$literal' });")
                }
                'fail' {
                    Add-CodeLine $Output $pad "throw new Error('rsat2pw: $literal');"
                }
            }
        }

        default { throw "unhandled action '$($Action.Op)'" }
    }
}

function Add-RuntimeCall {
    param($Output, [string] $Pad, [string] $Expression)
    Add-CodeLine $Output $Pad "await d365.$Expression;"
}

function Add-CodeLine {
    param($Output, [string] $Pad, [string] $Text)
    [void] $Output.Append($Pad)
    [void] $Output.Append($Text)
    [void] $Output.Append("`n")
}
