// ---------------------------------------------------------------------------
// Generated by rsat2pw from the Task Recorder recording "Confirm purchase order".
// 32 action(s), 1 unmapped - search for TODO(rsat2pw).
//
// Do not hand-edit: regenerate instead. Durable changes belong in the runtime
// helper (runtime/d365.ts), which is where every D365 quirk is handled.
// ---------------------------------------------------------------------------

import { test } from '@playwright/test';
import { D365 } from '../runtime/d365';
import { cases } from './ConfirmPurchaseOrder.data';

for (const params of cases) {
  test(`Confirm purchase order [${params.__case}]`, async ({ page }) => {
    const d365 = await D365.open(page);

    await test.step('Find the purchase order', async () => {
      await d365.navigate('PurchTableListPage', 'Display');
      await d365.withForm('PurchTable', async () => {
        // rsat2pw: skipped 'CommandUserAction:GetFilters' - opens the filter pane; filter() does that itself
        await d365.filter('SystemDefinedFilterManager', 'PurchId', 'Purchase order', 'Is', params.PurchId);
        await d365.selectRow('Grid', 2);
        await d365.openRow('Grid');
      });
    });

    await test.step('Check the delivery details', async () => {
      // The delivery date must fall inside the open period.
      // Sub-task: Delivery details. (Begin)
      await d365.withForm('PurchTable', async () => {
        await d365.shortcut('ViewEdit');
        await d365.tab('PurchaseTab');
        await d365.setField('PurchTable_DeliveryDate', params.PurchTable_DeliveryDate, 'Date');
        await d365.openLookup('PurchTable_DlvMode');
        await d365.withForm('PurchTable_DlvMode_Lookup', async () => {
          await d365.selectRow('LookupGrid', 1);
        });
        await d365.commitLookup('PurchTable_DlvMode');
        await d365.setGridCell('PurchLineGrid', 'PurchLine_PurchQty', 0, params.PurchLine_PurchQty, 'Real');
        await d365.setField('PurchParmTable_Printout', params.PurchParmTable_Printout, 'CheckBox');
      });
    });

    await test.step('Set the procurement category', async () => {
      await d365.withForm('PurchTable', async () => {
        await d365.openLookup('PurchLine_ProcurementCategory');
        await d365.withForm('EcoResCategorySingleLookup', async () => {
          await d365.selectTreeItem('ctrlFormTree', params.ctrlFormTree);
        });
        await d365.commitLookup('PurchLine_ProcurementCategory');
      });
    });

    await test.step('Confirm the order', async () => {
      await d365.withForm('PurchTable', async () => {
        await d365.click('PurchFormLetter_PurchOrderJournal', 'MenuItemButton');
        // TODO(rsat2pw): could not map Task Recorder action 'CommandUserAction:SelectForAdd' (CommandName=SelectForAdd, ControlName=Grid, ControlType=Grid, Description=Select Grid to add a field to it.)
        test.info().annotations.push({ type: 'rsat2pw-todo', description: 'could not map Task Recorder action \'CommandUserAction:SelectForAdd\' (CommandName=SelectForAdd, ControlName=Grid, ControlType=Grid, Description=Select Grid to add a field to it.)' });
        await d365.click('Yes', 'CommandButton');
        await d365.closeForm();
      });
    });
  });
}