// ---------------------------------------------------------------------------
// Generated by rsat2pw from the Task Recorder recording "Create customer".
// 18 action(s), 1 unmapped - search for TODO(rsat2pw).
//
// Do not hand-edit: regenerate instead. Durable changes belong in the runtime
// helper (runtime/d365.ts), which is where every D365 quirk is handled.
// ---------------------------------------------------------------------------

import { test } from '@playwright/test';
import { D365 } from '../runtime/d365';
import { cases } from './CreateCustomer.data';

for (const params of cases) {
  test(`Create customer [${params.__case}]`, async ({ page }) => {
    const d365 = await D365.open(page);

    await test.step('Go to All customers', async () => {
      await d365.navigate('CustTableListPage', 'Display');
      await d365.enterForm('CustTableListPage');
    });

    await test.step('Create a new customer', async () => {
      await d365.command('New');
      await d365.withDialog('Create customer', async () => {
        await d365.setField('CustAccount', params.Customer_account);
        await d365.setField('NameRef_Name', params.Customer_name);
        await d365.lookup('CustGroup', params.Customer_group);
        await d365.setField('CustTable_CreditMax', '50000');
        await d365.command('OK');
      });
    });

    await test.step('Add a primary address line', async () => {
      await d365.setGridCell('LogisticsPostalAddressGrid', 'Street', 0, params.Street);
      await d365.setGridCell('LogisticsPostalAddressGrid', 'City', 0, 'Redmond');
    });

    await test.step('Save and verify the customer was created', async () => {
      await d365.command('Save');
      await d365.expectValue('CustAccount', params.Customer_account);
      // TODO(rsat2pw): could not map Task Recorder action 'ExportToExcelUserAction' (ControlName=ExportToExcelButton, OfficeTemplate=CustomerV3)
      test.info().annotations.push({ type: 'rsat2pw-todo', description: 'could not map Task Recorder action \'ExportToExcelUserAction\' (ControlName=ExportToExcelButton, OfficeTemplate=CustomerV3)' });
    });
  });
}