// ---------------------------------------------------------------------------
// Generated by rsat2pw. Test data source: fixtures/ConfirmPurchaseOrder-params.xlsx [Parameters]
//
// This is the RSAT parameter file's replacement. Add rows here (or regenerate
// from an updated workbook) to run the same recording against more data.
// ---------------------------------------------------------------------------

export type Params = {
  PurchId: string;
  PurchTable_DeliveryDate: string;
  PurchLine_PurchQty: string;
  PurchParmTable_Printout: string;
  ctrlFormTree: string;
};

export const cases: (Params & { __case: string })[] = [
  {
    __case: 'confirm with printout',
    PurchId: '000123',
    PurchTable_DeliveryDate: '9/30/2026',
    PurchLine_PurchQty: '12',
    PurchParmTable_Printout: 'true',
    ctrlFormTree: 'ALL (ALL)\\Office supplies (Office supplies)',
  },
  {
    __case: 'confirm quietly',
    PurchId: '000124',
    PurchTable_DeliveryDate: '10/14/2026',
    PurchLine_PurchQty: '3',
    PurchParmTable_Printout: 'false',
    ctrlFormTree: 'ALL (ALL)\\Office supplies (Office supplies)',
  },
];