// ---------------------------------------------------------------------------
// Generated by rsat2pw. Test data source: fixtures/CreateCustomer-params.xlsx [Parameters]
//
// This is the RSAT parameter file's replacement. Add rows here (or regenerate
// from an updated workbook) to run the same recording against more data.
// ---------------------------------------------------------------------------

export type Params = {
  Customer_account: string;
  Customer_name: string;
  Customer_group: string;
  Street: string;
};

export const cases: (Params & { __case: string })[] = [
  {
    __case: 'domestic retail',
    Customer_account: 'US-9001',
    Customer_name: 'Contoso Retail',
    Customer_group: '10',
    Street: '123 Sample Way',
  },
  {
    __case: 'export wholesale',
    Customer_account: 'US-9002',
    Customer_name: 'Fabrikam Export',
    Customer_group: '20',
    Street: '9 Harbour Rd',
  },
];