using System.Globalization;
using System.Text;

namespace Rsat2Pw;

public enum OnUnsupported
{
    Annotate,

    Fail,

    Comment,
}

public sealed class Output
{
    public required string Spec { get; init; }

    public required string Data { get; init; }

    public required string Stem { get; init; }
}

public static class Codegen
{
    public static OnUnsupported? ParseOnUnsupported(string value) =>
        value.ToLowerInvariant() switch
        {
            "annotate" => OnUnsupported.Annotate,
            "fail" => OnUnsupported.Fail,
            "comment" => OnUnsupported.Comment,
            _ => null,
        };

    public static Output Generate(TestCase testCase, Cases cases, OnUnsupported onUnsupported)
    {
        var stem = Casing.ToPascalCase(testCase.Name);

        var body = new StringBuilder();
        EmitAll(testCase.Actions, 2, onUnsupported, body);

        var spec = RenderSpec(testCase, stem, body.ToString().TrimEnd());
        var data = RenderData(cases);

        return new Output { Spec = spec, Data = data, Stem = stem };
    }

    private static string RenderSpec(TestCase testCase, string stem, string body)
    {
        var actionCount = testCase.ActionCount();
        var todoCount = testCase.UnsupportedCount();

        var recordingName = Ir.CommentSafe(testCase.Name);
        var testTitle = Ir.EscapeTemplateLiteral(testCase.Name);

        var todoSuffix = todoCount > 0
            ? $", {todoCount.ToString(CultureInfo.InvariantCulture)} unmapped - search for TODO(rsat2pw)"
            : "";

        var builder = new StringBuilder();
        builder.Append("// ---------------------------------------------------------------------------\n");
        builder.Append($"// Generated by rsat2pw from the Task Recorder recording \"{recordingName}\".\n");
        builder.Append($"// {actionCount.ToString(CultureInfo.InvariantCulture)} action(s){todoSuffix}.\n");
        builder.Append("//\n");
        builder.Append("// Do not hand-edit: regenerate instead. Durable changes belong in the runtime\n");
        builder.Append("// helper (runtime/d365.ts), which is where every D365 quirk is handled.\n");
        builder.Append("// ---------------------------------------------------------------------------\n");
        builder.Append('\n');
        builder.Append("import { test } from '@playwright/test';\n");
        builder.Append("import { D365 } from '../runtime/d365';\n");
        builder.Append($"import {{ cases }} from './{stem}.data';\n");
        builder.Append('\n');
        builder.Append("for (const params of cases) {\n");
        builder.Append($"  test(`{testTitle} [${{params.__case}}]`, async ({{ page }}) => {{\n");
        builder.Append("    const d365 = await D365.open(page);\n");
        builder.Append('\n');
        builder.Append(body);
        builder.Append('\n');
        builder.Append("  });\n");
        builder.Append('}');

        return builder.ToString();
    }

    private static string RenderData(Cases cases)
    {
        var builder = new StringBuilder();
        builder.Append("// ---------------------------------------------------------------------------\n");
        builder.Append($"// Generated by rsat2pw. Test data source: {cases.Source}\n");
        builder.Append("//\n");
        builder.Append("// This is the RSAT parameter file's replacement. Add rows here (or regenerate\n");
        builder.Append("// from an updated workbook) to run the same recording against more data.\n");
        builder.Append("// ---------------------------------------------------------------------------\n");
        builder.Append('\n');
        builder.Append("export type Params = {");

        foreach (var field in cases.Fields)
        {
            builder.Append($"\n  {field}: string;");
        }

        builder.Append("\n};\n");
        builder.Append('\n');
        builder.Append("export const cases: (Params & { __case: string })[] = [");

        foreach (var row in cases.Rows)
        {
            builder.Append("\n  {");
            builder.Append($"\n    __case: '{Ir.EscapeTs(row.Label)}',");

            foreach (var field in cases.Fields)
            {
                var value = row.Values.TryGetValue(field, out var v) ? v : "";
                builder.Append($"\n    {field}: '{Ir.EscapeTs(value)}',");
            }

            builder.Append("\n  },");
        }

        builder.Append("\n];");

        return builder.ToString();
    }

    private static void EmitAll(
        IReadOnlyList<Action> actions,
        int indent,
        OnUnsupported onUnsupported,
        StringBuilder output)
    {
        foreach (var action in actions)
        {
            Emit(action, indent, onUnsupported, output);
        }
    }

    private static void Emit(Action action, int indent, OnUnsupported onUnsupported, StringBuilder output)
    {
        var pad = new string(' ', indent * 2);

        switch (action)
        {
            case Action.Navigate a:
                Line(output, pad, $"await d365.navigate('{Ir.EscapeTs(a.MenuItem)}', '{Ir.KindAsString(a.Kind)}');");
                break;

            case Action.EnterForm a:
                Line(output, pad, $"await d365.enterForm('{Ir.EscapeTs(a.Form)}');");
                break;

            case Action.LeaveForm a:
                Line(output, pad, $"await d365.leaveForm('{Ir.EscapeTs(a.Form)}');");
                break;

            case Action.SetValue a:
                Line(output, pad, $"await d365.setField('{Ir.EscapeTs(a.Control)}', {a.Value.ToTs()});");
                break;

            case Action.SetGridValue a:
                Line(
                    output,
                    pad,
                    $"await d365.setGridCell('{Ir.EscapeTs(a.Grid)}', '{Ir.EscapeTs(a.Column)}', "
                    + $"{a.Row.ToString(CultureInfo.InvariantCulture)}, {a.Value.ToTs()});");
                break;

            case Action.Click a:
                Line(output, pad, $"await d365.click('{Ir.EscapeTs(a.Control)}');");
                break;

            case Action.Command a:
                Line(output, pad, $"await d365.command('{Ir.EscapeTs(a.Name)}');");
                break;

            case Action.Lookup a:
                Line(output, pad, $"await d365.lookup('{Ir.EscapeTs(a.Control)}', {a.Value.ToTs()});");
                break;

            case Action.Validate a:
                Line(output, pad, $"await d365.expectValue('{Ir.EscapeTs(a.Control)}', {a.Expected.ToTs()});");
                break;

            case Action.Dialog a:
                Line(output, pad, $"await d365.withDialog('{Ir.EscapeTs(a.Name)}', async () => {{");
                EmitAll(a.Children, indent + 1, onUnsupported, output);
                Line(output, pad, "});");
                break;

            case Action.Step a:
                Line(output, pad, $"await test.step('{Ir.EscapeTs(a.Label)}', async () => {{");
                EmitAll(a.Children, indent + 1, onUnsupported, output);
                Line(output, pad, "});");
                output.Append('\n');
                break;

            case Action.Unsupported a:
            {
                var message = $"could not map Task Recorder action '{a.RawKind}' ({a.Detail})";

                var literal = Ir.EscapeTs(message);
                Line(output, pad, $"// TODO(rsat2pw): {Ir.CommentSafe(message)}");

                switch (onUnsupported)
                {
                    case OnUnsupported.Comment:
                        break;

                    case OnUnsupported.Annotate:
                        Line(
                            output,
                            pad,
                            $"test.info().annotations.push({{ type: 'rsat2pw-todo', description: '{literal}' }});");
                        break;

                    case OnUnsupported.Fail:
                        Line(output, pad, $"throw new Error('rsat2pw: {literal}');");
                        break;
                }

                break;
            }

            default:
                throw new InvalidOperationException($"unhandled action {action.GetType().Name}");
        }
    }

    private static void Line(StringBuilder output, string pad, string text)
    {
        output.Append(pad);
        output.Append(text);
        output.Append('\n');
    }
}
