using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Rsat2Pw;

public sealed class Coverage
{
    [JsonPropertyName("actions")]
    public int Actions { get; init; }

    [JsonPropertyName("translated")]
    public int Translated { get; init; }

    [JsonPropertyName("not_translated")]
    public int NotTranslated { get; init; }

    public double Percent() => Actions == 0 ? 100.0 : (double)Translated / Actions * 100.0;
}

public sealed class UnmappedKind
{
    [JsonPropertyName("raw_kind")]
    public required string RawKind { get; init; }

    [JsonPropertyName("count")]
    public int Count { get; set; }

    [JsonPropertyName("props")]
    public SortedDictionary<string, string> Props { get; init; } = new(StringComparer.Ordinal);
}

public sealed class VariableUse
{
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("default")]
    public required string Default { get; init; }

    [JsonPropertyName("referenced")]
    public bool Referenced { get; init; }

    [JsonPropertyName("in_test_data")]
    public bool InTestData { get; init; }
}

public sealed class OutlineEntry
{
    [JsonPropertyName("depth")]
    public int Depth { get; init; }

    [JsonPropertyName("op")]
    public required string Op { get; init; }

    [JsonPropertyName("detail")]
    public required string Detail { get; init; }

    [JsonPropertyName("translated")]
    public bool Translated { get; init; }
}

public sealed class Report
{
    [JsonPropertyName("recording")]
    public required string Recording { get; init; }

    [JsonPropertyName("coverage")]
    public required Coverage Coverage { get; init; }

    [JsonPropertyName("translated_by_op")]
    public SortedDictionary<string, int> TranslatedByOp { get; init; } = new(StringComparer.Ordinal);

    [JsonPropertyName("not_translated")]
    public List<UnmappedKind> NotTranslated { get; init; } = [];

    [JsonPropertyName("variables")]
    public List<VariableUse> Variables { get; init; } = [];

    [JsonPropertyName("test_cases")]
    public int TestCases { get; init; }

    [JsonPropertyName("test_data_source")]
    public required string TestDataSource { get; init; }

    [JsonPropertyName("outline")]
    public List<OutlineEntry> Outline { get; init; } = [];

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    public string ToJson() => JsonSerializer.Serialize(this, JsonOptions);

    public string ToMarkdown()
    {
        var s = new StringBuilder();
        var c = Coverage;

        s.Append($"# Conversion report: {Recording}\n\n");
        s.Append("Generated by `rsat2pw`. Regenerate this alongside the spec whenever\n");
        s.Append("the recording or the mapping table changes.\n\n");

        s.Append("## Coverage\n\n");
        s.Append("| | |\n|---|---|\n");
        s.Append($"| Actions | {c.Actions.ToString(CultureInfo.InvariantCulture)} |\n");
        s.Append(CultureInfo.InvariantCulture, $"| Translated | {c.Translated} ({c.Percent():F1}%) |\n");
        s.Append($"| Not translated | {c.NotTranslated.ToString(CultureInfo.InvariantCulture)} |\n");
        s.Append($"| Test cases | {TestCases.ToString(CultureInfo.InvariantCulture)} (from {TestDataSource}) |\n\n");

        if (c.NotTranslated == 0)
        {
            s.Append("Every recorded action mapped to a runtime call.\n\n");
        }

        s.Append("## Translated\n\n");
        if (TranslatedByOp.Count == 0)
        {
            s.Append("_Nothing._\n\n");
        }
        else
        {
            s.Append("| Emitted call | Count |\n|---|---:|\n");
            foreach (var (op, n) in TranslatedByOp)
            {
                var call = op.Contains('.', StringComparison.Ordinal) ? $"{op}()" : $"d365.{op}()";
                s.Append($"| `{call}` | {n.ToString(CultureInfo.InvariantCulture)} |\n");
            }

            s.Append('\n');
        }

        s.Append("## Not translated\n\n");
        if (NotTranslated.Count == 0)
        {
            s.Append("_Nothing — full coverage._\n\n");
        }
        else
        {
            s.Append(
                "Each heading is a Task Recorder action type with no rule in "
                + "`src/lower.rs`.\nThe properties are everything the recorder "
                + "supplied, which is what a new\nmapping rule keys off.\n\n");

            foreach (var kind in NotTranslated)
            {
                var plural = kind.Count == 1 ? "" : "s";
                s.Append($"### `{kind.RawKind}` — {kind.Count.ToString(CultureInfo.InvariantCulture)} occurrence{plural}\n\n");

                if (kind.Props.Count == 0)
                {
                    s.Append("_No properties recorded._\n\n");
                }
                else
                {
                    s.Append("| Property | Example value |\n|---|---|\n");
                    foreach (var (key, value) in kind.Props)
                    {
                        s.Append($"| `{key}` | {MdCell(value)} |\n");
                    }

                    s.Append('\n');
                }
            }
        }

        s.Append("## Test data\n\n");
        if (Variables.Count == 0)
        {
            s.Append("_The recording declared no variables._\n\n");
        }
        else
        {
            s.Append("| Variable | Used by an action | In test data | Recorded default |\n");
            s.Append("|---|---|---|---|\n");
            foreach (var v in Variables)
            {
                s.Append($"| `{v.Name}` | {YesNo(v.Referenced)} | {YesNo(v.InTestData)} | {MdCell(v.Default)} |\n");
            }

            s.Append('\n');

            if (Variables.Any(v => v.Referenced && !v.InTestData))
            {
                s.Append(
                    "> Variables used by an action but absent from the test data fall back to\n"
                    + "> the recorded default, so the spec still compiles and runs.\n\n");
            }
        }

        s.Append("## Translation outline\n\n");
        s.Append("The recording in order. `!!` marks an action that was not translated.\n\n");
        s.Append("```\n");
        foreach (var e in Outline)
        {
            var marker = e.Translated ? "   " : "!! ";
            var indent = string.Concat(Enumerable.Repeat("  ", e.Depth));
            s.Append($"{marker}{indent}{e.Op} {e.Detail}\n");
        }

        s.Append("```\n");

        return s.ToString();
    }

    private static string YesNo(bool b) => b ? "yes" : "no";

    private static string MdCell(string s)
    {
        var flat = s
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal)
            .Replace("|", "\\|", StringComparison.Ordinal);

        return string.IsNullOrWhiteSpace(flat) ? "_(empty)_" : $"`{flat}`";
    }
}

public static class Reporter
{
    public static Report Build(TestCase testCase, Cases cases)
    {
        var translatedByOp = new SortedDictionary<string, int>(StringComparer.Ordinal);
        var unmapped = new SortedDictionary<string, UnmappedKind>(StringComparer.Ordinal);
        var outline = new List<OutlineEntry>();

        Walk(testCase.Actions, 0, translatedByOp, unmapped, outline);

        var notTranslated = unmapped.Values.Sum(u => u.Count);
        var actions = testCase.ActionCount();

        var referenced = ReferencedVariables(testCase.Actions);
        var variables = testCase.Variables
            .Select(v => new VariableUse
            {
                Name = v.Name,
                Default = v.Default,
                Referenced = referenced.Contains(v.Name, StringComparer.Ordinal),
                InTestData = cases.Fields.Contains(v.Name, StringComparer.Ordinal),
            })
            .ToList();

        return new Report
        {
            Recording = testCase.Name,
            Coverage = new Coverage
            {
                Actions = actions,
                Translated = Math.Max(0, actions - notTranslated),
                NotTranslated = notTranslated,
            },
            TranslatedByOp = translatedByOp,
            NotTranslated = unmapped.Values.ToList(),
            Variables = variables,
            TestCases = cases.Rows.Count,
            TestDataSource = cases.Source,
            Outline = outline,
        };
    }

    private static void Walk(
        IReadOnlyList<Action> actions,
        int depth,
        SortedDictionary<string, int> byOp,
        SortedDictionary<string, UnmappedKind> unmapped,
        List<OutlineEntry> outline)
    {
        foreach (var action in actions)
        {
            var translated = action is not Action.Unsupported;

            outline.Add(new OutlineEntry
            {
                Depth = depth,
                Op = action.OpName(),
                Detail = action.Summary(),
                Translated = translated,
            });

            if (action is Action.Unsupported unsupportedAction)
            {
                if (!unmapped.TryGetValue(unsupportedAction.RawKind, out var entry))
                {
                    entry = new UnmappedKind { RawKind = unsupportedAction.RawKind };
                    unmapped[unsupportedAction.RawKind] = entry;
                }

                entry.Count += 1;

                foreach (var (key, value) in unsupportedAction.Props)
                {
                    entry.Props.TryAdd(key, value);
                }
            }
            else
            {
                var op = action.OpName();
                byOp[op] = byOp.TryGetValue(op, out var count) ? count + 1 : 1;
            }

            Walk(action.ChildActions(), depth + 1, byOp, unmapped, outline);
        }
    }

    private static List<string> ReferencedVariables(IReadOnlyList<Action> actions)
    {
        var result = new List<string>();

        static void Note(Value value, List<string> result)
        {
            if (value is Value.Variable v && !result.Contains(v.Name, StringComparer.Ordinal))
            {
                result.Add(v.Name);
            }
        }

        void Walk(IReadOnlyList<Action> items)
        {
            foreach (var action in items)
            {
                switch (action)
                {
                    case Action.SetValue a:
                        Note(a.Value, result);
                        break;
                    case Action.SetGridValue a:
                        Note(a.Value, result);
                        break;
                    case Action.Lookup a:
                        Note(a.Value, result);
                        break;
                    case Action.Validate a:
                        Note(a.Expected, result);
                        break;
                }

                Walk(action.ChildActions());
            }
        }

        Walk(actions);
        return result;
    }
}
